# Generated by Django 4.0.1 on 2022-09-04 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plankiHomePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=170, verbose_name='Название')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категорию Комплектующих',
                'verbose_name_plural': 'Категории Комплектующих',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategorySlats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=170, verbose_name='Название')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категорию Планок',
                'verbose_name_plural': 'Категории Планок',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Impressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=170, verbose_name='Название')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='plankiHomePage/images/impressions/%Y/%m/%d', verbose_name='Фото')),
                ('stock', models.PositiveIntegerField(verbose_name='Остаток продукта')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Оттиск',
                'verbose_name_plural': 'Оттиски',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Jettons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=170, verbose_name='Название')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='plankiHomePage/images/jettons/%Y/%m/%d', verbose_name='Фото')),
                ('stock', models.PositiveIntegerField(verbose_name='Остаток продукта')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Жетон',
                'verbose_name_plural': 'Жетоны',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sashes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=170, verbose_name='Название')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='plankiHomePage/images/sashes/%Y/%m/%d', verbose_name='Фото')),
                ('stock', models.PositiveIntegerField(verbose_name='Остаток продукта')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Лента',
                'verbose_name_plural': 'Ленты',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Slats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=170, verbose_name='Название')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='plankiHomePage/images/slats/%Y/%m/%d', verbose_name='Фото')),
                ('stock', models.PositiveIntegerField(verbose_name='Остаток продукта')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plankiHomePage.categoryslats', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Планка',
                'verbose_name_plural': 'Планки',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=170, verbose_name='Название')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='plankiHomePage/images/accessories/%Y/%m/%d', verbose_name='Фото')),
                ('stock', models.PositiveIntegerField(verbose_name='Остаток продукта')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plankiHomePage.categoryaccessories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Комплектующая',
                'verbose_name_plural': 'Комплектующие',
                'ordering': ['time_create', 'name'],
            },
        ),
    ]
