# Generated by Django 4.0.1 on 2022-09-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plankiHomePage', '0002_categoryaccessories_categoryslats_impressions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='category',
        ),
        migrations.DeleteModel(
            name='Impressions',
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='CategoryAccessories',
        ),
    ]
